# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Skeleton' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skeleton

end

target 'SkeletonKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkeletonKit

end
